name: podify
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  audioplayers: ^6.5.1
  dio: ^5.9.0
  file_saver: ^0.3.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_spinkit: ^5.2.2
  http: ^1.5.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
